name: LagRestart
main: at.yawk.bukkit.lagrestart.LagRestart
version: ${version}
description: Restart the server if TPS get too low
commands:
    lr:
        description: Display TPS, toggle LagRestart, schedule restart manually
        usage: /lr [on|off|schedule]
        permission: lagrestart.display
